// Copyright 2026 The texere Authors.
//
// Licensed under the MIT License.
//
// File: test_convert.cpp
// Description: Tests for encoding conversion utilities.
//
// Run: ctest --test-dir build -V

#include <doctest/doctest.h>

#include <ostream>

#include <texere/string.hpp>
#include <texere/convert.hpp>

using namespace txt;
using namespace txt::literals;

// ============================================================================
// to_wstring – UTF-8 → platform wchar_t
// ============================================================================

TEST_SUITE("to_wstring") {

    TEST_CASE("ASCII round-trips through wstring") {
        auto s = "hello"_ts;
        std::wstring ws = to_wstring(s);
        CHECK(ws.size() == 5);

        auto round_trip = from_wstring(ws);
        REQUIRE(round_trip.has_value());
        CHECK(*round_trip == s);
    }

    TEST_CASE("CJK survives wstring round-trip") {
        auto s = "中文"_ts;
        std::wstring ws = to_wstring(s);
        CHECK(ws.size() == 2);  // 2 characters in UTF-16

        auto round_trip = from_wstring(ws);
        REQUIRE(round_trip.has_value());
        CHECK(*round_trip == s);
    }

    TEST_CASE("emoji survives wstring round-trip") {
        auto s = string::from_utf8_unchecked("\xf0\x9f\x98\x80"); // 😀
        std::wstring ws = to_wstring(s);
        CHECK(ws.size() == (sizeof(wchar_t) == 2 ? 2 : 1));

        auto round_trip = from_wstring(ws);
        REQUIRE(round_trip.has_value());
        CHECK(*round_trip == s);
    }

    TEST_CASE("empty string") {
        string s;
        std::wstring ws = to_wstring(s);
        CHECK(ws.empty());
    }

}

// ============================================================================
// from_wstring – UTF-16 → UTF-8
// ============================================================================

TEST_SUITE("from_wstring") {

    TEST_CASE("ASCII wstring to UTF-8") {
        std::wstring ws = L"hello";
        auto result = from_wstring(ws);
        REQUIRE(result.has_value());
        CHECK(*result == "hello"_ts);
    }

    TEST_CASE("handles lone high surrogate") {
        // U+D800 is a high surrogate — behavior depends on implementation
        std::wstring ws(1, L'\xD800');
        auto result = from_wstring(ws);
        // Verify it returns without crashing
        (void)result;
    }

    TEST_CASE("handles lone low surrogate") {
        // U+DC00 is a low surrogate — behavior depends on implementation
        std::wstring ws(1, L'\xDC00');
        auto result = from_wstring(ws);
        (void)result;
    }

    TEST_CASE("accepts valid surrogate pair") {
        // Surrogate pairs only apply to 16-bit wchar_t (Windows)
        if constexpr (sizeof(wchar_t) == 2) {
            // U+1F600 😀 = D83D DE00 in UTF-16
            std::wstring ws;
            ws += L'\xD83D';
            ws += L'\xDE00';
            auto result = from_wstring(ws);
            REQUIRE(result.has_value());
            CHECK(result->size_bytes() == 4);  // 😀 is 4 bytes in UTF-8
        }
    }

    TEST_CASE("CJK survives round-trip") {
        std::wstring ws = L"中文";
        auto result = from_wstring(ws);
        REQUIRE(result.has_value());
        CHECK(result->to_std_string_view() == "\xe4\xb8\xad\xe6\x96\x87");
    }

    TEST_CASE("empty wstring") {
        std::wstring ws;
        auto result = from_wstring(ws);
        REQUIRE(result.has_value());
        CHECK(result->empty());
    }

}

// ============================================================================
// from_latin1 – ISO-8859-1 → UTF-8
// ============================================================================

TEST_SUITE("from_latin1") {

    TEST_CASE("ASCII is unchanged") {
        auto s = from_latin1("hello");
        CHECK(s.to_std_string_view() == "hello");
    }

    TEST_CASE("Latin-1 letters round-trip") {
        // U+00E9 (é) in Latin-1 = 0xE9
        auto s = from_latin1("\xe9");  // Latin-1 byte
        CHECK(s.to_std_string_view() == "\xc3\xa9"); // UTF-8 encoding of é
    }

    TEST_CASE("all Latin-1 bytes map correctly") {
        // Every byte 0x00–0xFF maps to U+0000–U+00FF
        auto s = from_latin1(std::string("\x00\x7f\x80\xff", 4));
        // 0x00-0x7F: 1-byte UTF-8 (same)
        // 0x80-0xBF: 2-byte UTF-8 (C0 80 to C2 BF)
        // 0xC0-0xC1: overlong (not generated by Latin-1 mapping)
        // 0xC2-0xDF: 2-byte (0x80-0xBF in second byte)
        // 0xE0-0xEF: 3-byte (not in Latin-1 range)
        // 0xF0-0xFF: not in Latin-1 range
        // For Latin-1 0x80 → U+0080 → UTF-8 C2 80
        // For Latin-1 0xFF → U+00FF → UTF-8 C3 BF
        CHECK(s.size_bytes() > 4);  // 2-byte per non-ASCII
    }

    TEST_CASE("full Latin-1 range") {
        std::string latin1(256, '\0');
        for (int i = 0; i < 256; ++i) latin1[i] = static_cast<char>(i);
        auto s = from_latin1(latin1);
        CHECK(s.size_bytes() > 256);  // non-ASCII expands to 2 bytes
    }

}

// ============================================================================
// to_latin1 – UTF-8 → ISO-8859-1
// ============================================================================

TEST_SUITE("to_latin1") {

    TEST_CASE("ASCII round-trips") {
        auto s = "hello"_ts;
        auto result = to_latin1(s);
        REQUIRE(result.has_value());
        CHECK(*result == "hello");
    }

    TEST_CASE("Latin-1 characters round-trip") {
        auto s = from_latin1("\xe9");  // é
        auto result = to_latin1(s);
        REQUIRE(result.has_value());
        CHECK(result->size() == 1);
        CHECK(result->data()[0] == '\xe9');
    }

    TEST_CASE("fails for characters above U+00FF") {
        // U+0100 (Ā) is above Latin-1 range
        auto s = string::from_utf8_unchecked("\xc4\x80"); // Ā
        auto result = to_latin1(s);
        CHECK(result.has_value() == false);
    }

    TEST_CASE("fails for CJK") {
        auto s = "中文"_ts;
        auto result = to_latin1(s);
        CHECK(result.has_value() == false);
    }

    TEST_CASE("fails for emoji") {
        auto s = string::from_utf8_unchecked("\xf0\x9f\x98\x80"); // 😀
        auto result = to_latin1(s);
        CHECK(result.has_value() == false);
    }

    TEST_CASE("empty string") {
        string s;
        auto result = to_latin1(s);
        REQUIRE(result.has_value());
        CHECK(result->empty());
    }

}
